version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biztelai-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - DATASET_PATH=/app/data/BiztelAI_DS_Dataset_Mar'25.json
      - OUTPUT_DIR=/app/output
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_for_development}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-default_jwt_secret_key_for_development}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS:-24}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 2 --timeout 60 api_server:app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  nginx:
    image: nginx:1.21-alpine
    container_name: biztelai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api

networks:
  default:
    name: biztelai-network 